const classesJson = [
  { "code": "MA531", "name": "ALGEBRA VET LINEAR P/COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "MA026", "name": "CALCULO DIFERENCIAL E INTEGRAL 1", "type": "OBRIG", "ch": 60, "credits": 4, "score": -1 },
  { "code": "IF668", "name": "INTRODUCAO A COMPUTACAO", "type": "OBRIG", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF669", "name": "INTRODUCAO A PROGRAMACAO", "type": "OBRIG", "ch": 120, "credits": 6, "score": -1 },
  { "code": "IF670", "name": "MATEMAT DISCRETA P/COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF672", "name": "ALGORITMOS E ESTRUTURAS DE DADOS", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "ET586", "name": "ESTATIST PROBABILIDADE COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "FI582", "name": "FISICA PARA COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF673", "name": "LOGICA PARA COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF675", "name": "SISTEMAS DIGITAIS", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF679", "name": "INFORMATICA E SOCIEDADE", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF678", "name": "INFRA-ESTRUTURA DE COMUNICACAO", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF674", "name": "INFRA-ESTRUTURA DE HARDWARE", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF677", "name": "INFRA-ESTRUTURA DE SOFTWARE", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "LE530", "name": "INGLES PARA COMPUTACAO", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF682", "name": "ENGENHARIA SOFTWARE E SISTEMAS", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF685", "name": "GERENCIAMENTO DADOS E INFORMACAO", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF689", "name": "INFORMATICA TEORICA", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF681", "name": "INTERFACES USUARIO-MAQUINA", "type": "OBRIG", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF680", "name": "PROCESSAMENTO GRAFICO", "type": "OBRIG", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF684", "name": "SISTEMAS INTELIGENTES", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF690", "name": "HISTORIA E FUTURO DA COMPUTACAO", "type": "OBRIG", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF687", "name": "INTRODUÇÃO A MULTIMIDIA", "type": "OBRIG", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF676", "name": "METODOL EXPRESSAO TEC-CIENTIFICA", "type": "OBRIG", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF686", "name": "PARADIGMAS LING.COMPUTACIONAIS", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF683", "name": "PROJETO DE DESENVOLVIMENTO", "type": "OBRIG", "ch": 75, "credits": 3, "score": -1 },
  { "code": "IF688", "name": "TEO.IMPLEMEN.LING. COMPUTACIONAIS", "type": "OBRIG", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF421", "name": "ESTAGIO 1", "type": "OBRIG", "ch": 300, "credits": 10, "score": -1 },
  { "code": "IF691", "name": "TRABALHO DE GRADUAÇÃO", "type": "OBRIG", "ch": 150, "credits": 7, "score": -1 },
  { "code": "IF869", "name": "ALGORITMOS E ESTRUTURAS DE DADOS AVANÇADOS", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "IF868", "name": "ALGORITMOS PARA STREAMS DE DADOS", "type": "ELETI", "ch": 60, "credits": 3, "score": -1 },
  { "code": "IF818", "name": "ANÁLISE E MINERAÇÃO DE REDES COMPLEXAS", "type": "ELETI", "ch": 60, "credits": 3, "score": -1 },
  { "code": "IF866", "name": "CRIATIVIDADE COMPUTACIONAL", "type": "ELETI", "ch": 60, "credits": 3, "score": -1 },
  { "code": "IF867", "name": "INTRODUÇÃO À APRENDIZAGEM PROFUNDA", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "IF744", "name": "ADM. DE SISTEMAS HETEROGENEOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF703", "name": "AGENTES AUTONOMOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF763", "name": "ALGEBRA LINEAR AVANC. COMPUTACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF766", "name": "ALGORITMOS DE APROXIMACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF731", "name": "AMBIENTES PROJETOS SIST.EMBUTIDOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF718", "name": "ANALISE E PROJETOS DE SISTEMAS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF752", "name": "ANALISE IMAG. VISAO COMPUTACIONAL", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF765", "name": "ANALISE NUMERICA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF699", "name": "APRENDIZAGEM DE MAQUINA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF705", "name": "AUTOMACAO INTELIGENTE", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF756", "name": "AUTORIA MULTIMIDIA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF742", "name": "AVALIACAO DESEMPENHO DE SISTEMAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF695", "name": "BANCO DE DADOS AVANÇADOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF694", "name": "BANCO DE DADOS DISTRIB. E MOVEIS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF764", "name": "CALCULO AVANCADO PARA COMPUTACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF715", "name": "CALCULO DE PROGRAMAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF792", "name": "COMERCIO ELETRONICO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF804", "name": "COMPARACAO ANALISE SEQUENCIAS DNA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF774", "name": "COMPLEXIDADE DESCRITIVA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF750", "name": "COMPUTACAO GRAFICA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF754", "name": "COMPUTACAO MUSICAL PROCESSAM.SOM", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF739", "name": "COMUNICAÇÃO SEM FIO", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF784", "name": "CONTABILIDADE FINANC. E GERENCIAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF835", "name": "CONTROLE E MANIPULACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF802", "name": "CONVERGENCIA DIGITAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF719", "name": "DESENVOLVIMENTO DE SISTEMAS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF780", "name": "ECONOMIA PARA EMPREENDEDOR", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF781", "name": "EMPREENDIMENTOS EM INFORMATICA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF701", "name": "ENG.CONHEC.SISTEMAS ESPECIALISTAS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF728", "name": "ENGENHARIA DE SISTEMAS EMBUTIDOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF800", "name": "ENGENHARIA SOFTWARE EDUCATIVOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF716", "name": "ESPECIF.REQUIS.VALIDACAO SISTEMAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "FI006", "name": "FISICA GERAL 1", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "FI007", "name": "FISICA GERAL 2", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "MA036", "name": "GEOMETRIA ANALITICA 1", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "IF741", "name": "GERENCIAMENTO DE REDES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF783", "name": "GESTAO DE NEGOCIOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF709", "name": "IMPLEMENTACAO SIST. OPERACIONAIS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF788", "name": "INICIACAO CIENTIFICA 1", "type": "ELETI", "ch": 75, "credits": 3, "score": -1 },
  { "code": "IF789", "name": "INICIACAO CIENTIFICA 2", "type": "ELETI", "ch": 75, "credits": 3, "score": -1 },
  { "code": "IF696", "name": "INTEG. DADOS WEB E WAREHOUSE", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF758", "name": "INTERFACES ADAPT. SISTEMAS MOVEIS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF865", "name": "INTERFACES GRÁFICAS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF803", "name": "INTRODUCAO A BIOLOGIA MOLECULAR", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF794", "name": "JOGOS AVANCADOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF772", "name": "LAMBDA CALCULO TEORIA TIPOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF773", "name": "LOGICAS NAO CLASSICAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF109", "name": "METODOS NUMERICOS", "type": "ELETI", "ch": 60, "credits": 4, "score": -1 },
  { "code": "IF796", "name": "MINERACAO DA WEB", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF782", "name": "NEGOCIOS ON LINE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF779", "name": "NOVA ECONOMIA E NOVA SOCIEDADE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF726", "name": "ORGANIZ. TECNOLOGIA COMPUTADORES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF797", "name": "OTIMIZACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF700", "name": "PERCEP. COMPUTAC.E RECONH. PADRAO", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF717", "name": "PLANEJ. GERENCIAMENTO DE PROJETOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF746", "name": "PROC.SIMUL.ESTOCAST.COMPUTACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF727", "name": "PROCESSADORES APLICAC. ESPECIFICA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF767", "name": "PROCESSAMENTO CADEIA CARACTERES", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF753", "name": "PROCESSAMENTO DE SINAIS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF759", "name": "PROCESSAMENTO DE VOZ", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF751", "name": "PROCESSAMENTO LINEAR DE IMAGENS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF704", "name": "PROCESSAMENTO LINGUAGEM NATURAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF785", "name": "PROFICIENCIA EM INGLES 1", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF786", "name": "PROFICIENCIA EM INGLES 2", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF787", "name": "PROFICIENCIA EM INGLES 3", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF799", "name": "PROG.DECLARATIVA B.D.INTELIGENTES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF711", "name": "PROGRAM. CONCORRENTE DISTRIBUIDA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF710", "name": "PROGRAMACAO COM COMPONENTES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF708", "name": "PROGRAMACAO FUNCIONAL", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF712", "name": "PROGRAMACAO PARA INTERNET", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF692", "name": "PROJETO DE BANCO DE DADOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF734", "name": "PROJETO DE COMPILADORES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF725", "name": "PROJETO DE CPU", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF790", "name": "PROJETO DE MONITORIA 1", "type": "ELETI", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF791", "name": "PROJETO DE MONITORIA 2", "type": "ELETI", "ch": 45, "credits": 2, "score": -1 },
  { "code": "IF805", "name": "PROJETO EM BIO INFORMATICA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF793", "name": "PROJETO IMPLEMENTACAO DE JOGOS 2D", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF732", "name": "PROJETOS DE SISTEMAS EMBUTIDOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF729", "name": "PROTOTIP. DE CIRCUITOS INTEGRADOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF720", "name": "QUALIDADE DE SOFTWARE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF755", "name": "REALIDADE VIRTUAL", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF962", "name": "RECUPERAÇÃO DE INFORMAÇÃO", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF738", "name": "REDES DE COMPUTADORES", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF702", "name": "REDES NEURAIS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF798", "name": "ROBOTICA", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF743", "name": "SEGURANCA DE SISTEMAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF723", "name": "SEM.ENG. SOFT LING. COMPUTACIONAL", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF713", "name": "SEMANTICA LINGUAGENS PROGRAMACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF707", "name": "SEMIN. EM INTELIGENCIA ARTIFICIAL", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF698", "name": "SEMIN. GERENC. DADOS E INFORMACAO", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF736", "name": "SEMIN.ARQUIT. SISTEMAS EMBUTIDOS", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF778", "name": "SEMINARIO EM INFORMATICA TEORICA", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF761", "name": "SEMINARIO EM MIDIAS E INTERFACES", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF748", "name": "SEMINARIO REDES SIST.DISTRIBUIDOS", "type": "ELETI", "ch": 45, "credits": 3, "score": -1 },
  { "code": "IF693", "name": "SIST.GERENC. DE BANCO DE DADOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF730", "name": "SISTEMA DE TEMPO REAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF721", "name": "SISTEMAS CRITICOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF740", "name": "SISTEMAS DE COMUNICACAO", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF714", "name": "SISTEMAS DE INFORMACAO", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF745", "name": "SISTEMAS MULTIMIDIA DISTRIBUIDOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF795", "name": "SISTEMAS SUPORTE DECIS.MIN.DADOS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF801", "name": "TECNOLOGIAS EDUCACIONAIS", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
  { "code": "IF771", "name": "TEORIA DA PROVA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF769", "name": "TEORIA DA RECURSAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF768", "name": "TEORIA DE GRAFOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF770", "name": "TEORIA DOS MODELOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF747", "name": "TOP. AVANC. REDES DE COMPUTADORES", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF807", "name": "TOP. AVANC.SIST.SUP.DECIS.MIN.WEB", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF737", "name": "TOP.AVANC. EM SISTEMAS EMBUTIDOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF777", "name": "TOP.AVANC. MATEMAT. COMPUTACIONAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF811", "name": "TOP.AVANC.ADMINIST.SIST.SEGURANCA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF735", "name": "TOP.AVANC.ARQUIT.DE COMPUTADORES", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF810", "name": "TOP.AVANC.EM NEGÓCIOS ONLINE E EMPREENDIMENTOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF812", "name": "TOP.AVANC.ENTRETENIMENTO DIGITAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF697", "name": "TOP.AVANC.GERENC.DADOS INFORMACAO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF809", "name": "TOP.AVANC.ROBOT.AUTOM.INTELIGENTE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF806", "name": "TOPICOS AVANC.EM BIO INFORMATICA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF706", "name": "TOPICOS AVANC.INTELEG.ARTIFICIAL", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF749", "name": "TOPICOS AVANC.SIST.DISTRIBUIDOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF808", "name": "TOPICOS AVANC.TECNOLOGIA ENSINO", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF775", "name": "TOPICOS AVANCADOS EM ALGORITMOS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF762", "name": "TOPICOS AVANCADOS EM INTERFACE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF760", "name": "TOPICOS AVANCADOS EM MIDIAS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF722", "name": "TOPICOS AVANCADOS ENG. SOFTWARE", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF776", "name": "TOPICOS AVANCADOS INF. TEORICA", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF724", "name": "TOPICOS AVAN. LING.COMPUTACIONAIS", "type": "ELETI", "ch": 75, "credits": 5, "score": -1 },
  { "code": "IF733", "name": "TRANSDUTORES", "type": "ELETI", "ch": 75, "credits": 4, "score": -1 },
]
